# Adapted from https://github.com/pandas-dev/pandas/blob/master/azure-pipelines.yml

# Global variables for all jobs
variables:
  VIRTUALENV: 'testvenv'
  JUNITXML: 'test-data.xml'
  CODECOV_TOKEN: 'cee0e505-c12e-4139-aa43-621fb16a2347'


jobs:

- template: continuous_integration/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
    matrix:
      py37_conda:
        VERSION_PYTHON: '3.7'
        PACKAGER: 'conda'
      py36_conda:
        VERSION_PYTHON: '3.6'
        PACKAGER: 'conda'
      py35_pip:
        VERSION_PYTHON: '3.5'
        PACKAGER: 'pip'


- template: continuous_integration/posix.yml
  parameters:
    name: Linux
    vmImage: ubuntu-16.04
    matrix:
      # Linux environment to test that packages that comes with Ubuntu Xenial
      # 16.04 are correctly handled.
      py35_np_atlas:
        PACKAGER: 'ubuntu'
        VERSION_PYTHON: '3.5'
      # Linux + Python 3.6
      py36_conda_openblas:
        PACKAGER: 'conda'
        VERSION_PYTHON: '3.6'
      # Linux environment to test the latest available dependencies and MKL.
      pylatest_conda:
        PACKAGER: 'conda'
        VERSION_PYTHON: '*'
      # Linux environment with no numpy.
      pylatest_conda_nonumpy:
        PACKAGER: 'conda'
        NO_NUMPY: 'true'
        VERSION_PYTHON: '*'

- template: continuous_integration/posix.yml
  parameters:
    name: macOS
    vmImage: xcode9-macos10.13
    matrix:
      pylatest_conda:
        PACKAGER: 'conda'
        VERSION_PYTHON: '*'